# Generated by Django 3.1 on 2020-10-01 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_yorumforum'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeYorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datelike', models.DateTimeField(auto_now=True, verbose_name='Beğenme Tarih')),
                ('toplam', models.CharField(max_length=100)),
                ('yorum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.yorumforum')),
                ('yorumbegenen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
