# Generated by Django 3.1 on 2020-10-18 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_likeyorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam', models.CharField(max_length=100)),
                ('datelike', models.DateTimeField(auto_now=True, verbose_name='Beğenme Tarihi')),
                ('begenen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
            ],
        ),
    ]
