# Generated by Django 3.1 on 2020-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_likeforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='BegenmeSayısı',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='forum',
            name='YorumSayısı',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
