# Generated by Django 3.1 on 2020-10-08 10:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField()),
                ('tarih', models.DateTimeField(auto_now=True, verbose_name='Eklenme Tarihi')),
                ('tags', models.CharField(max_length=175, verbose_name='Kategoriler')),
                ('haber_image', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
