# Generated by Django 3.1 on 2020-10-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0004_addfavorihaber'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='toplamBegenme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
