# Generated by Django 3.1 on 2020-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0005_haber_toplambegenme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='toplamBegenme',
            field=models.CharField(max_length=100),
        ),
    ]
