# Generated by Django 3.1 on 2020-10-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0007_auto_20201016_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='toplamYorum',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
