# Generated by Django 3.1 on 2020-10-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haberler', '0008_haber_toplamyorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReportHaber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daterep', models.DateTimeField(auto_now=True, verbose_name='Raport Tarih')),
                ('toplam', models.CharField(max_length=100)),
                ('sorun', models.CharField(choices=[('yanlısbilgi', 'Yanlış Bilgi İçeriyor'), ('cinseliçerik', '18 Yaş Üstü Uygunsuz İçerik'), ('spam', 'Spam'), ('nefretvekötü', 'Nefret ve Kötü Amaçlı')], default='Seçmedi', max_length=100, verbose_name='Sebep')),
                ('haber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.haber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
