# Generated by Django 3.1 on 2020-09-22 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oyunlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyun_isim', models.CharField(max_length=70, verbose_name='Oyun İsmi..')),
                ('bilgisayar_platform', models.BooleanField(default=False, verbose_name='Bilgisayar')),
                ('mobil_platform', models.BooleanField(default=False, verbose_name='Mobil')),
                ('konsol_platform', models.BooleanField(default=False, verbose_name='Oyun Konsolu')),
                ('kategoriler', models.CharField(max_length=200, verbose_name='Katogoriler')),
                ('geliştirici', models.CharField(max_length=200, verbose_name='Geliştirici')),
                ('cıkıs_tarih', models.DateField(verbose_name='Oyun Çıkış Tarihi')),
                ('türkce_dil', models.BooleanField(default=False, verbose_name='Türkçe Dil')),
                ('hakkında', ckeditor.fields.RichTextField()),
                ('game_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf')),
            ],
        ),
    ]
