# Generated by Django 3.1 on 2020-09-21 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogum_gunu', models.DateField(blank=True, null=True, verbose_name='Doğum Günü')),
                ('cinsiyet', models.CharField(choices=[('belirtmekistemiyor', 'Belirtmek İstemiyorum'), ('erkek', 'ERKEK'), ('kadın', 'KADIN')], default='belirtmekistemiyor', max_length=20)),
                ('hakkında', models.TextField(blank=True, max_length=400, null=True, verbose_name='hakkımda')),
                ('location', models.CharField(blank=True, default='Bilgi girilmemiş.', max_length=30, verbose_name='Konum')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğrafınız')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
