# Generated by Django 3.1 on 2020-09-24 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_mygame'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMyFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam', models.CharField(max_length=80)),
                ('eklenen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arkadasekle', to=settings.AUTH_USER_MODEL, verbose_name='eklenen')),
                ('ekleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eklearkadas', to=settings.AUTH_USER_MODEL, verbose_name='ekleyen')),
            ],
        ),
    ]
