# Generated by Django 3.1 on 2020-09-25 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_addmyfriends'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockMyFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam', models.CharField(max_length=80)),
                ('bloklanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blokarkadas', to=settings.AUTH_USER_MODEL, verbose_name='bloklanan')),
                ('bloklayan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arkadasblok', to=settings.AUTH_USER_MODEL, verbose_name='bloklayan')),
            ],
        ),
    ]
