# Generated by Django 3.1 on 2020-10-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_blockmyfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygame',
            name='dategame',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ekle Tarih'),
        ),
    ]
