# Generated by Django 3.1 on 2020-10-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mygame_dategame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='dategame',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ekle Tarih'),
        ),
    ]
