# Generated by Django 3.1 on 2020-10-23 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201023_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='dategame',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ekle Tarih'),
        ),
    ]
