# Generated by Django 3.1 on 2020-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201023_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='dategame',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ekle Tarih'),
        ),
    ]
