# Generated by Django 3.1 on 2020-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201023_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='dategame',
            field=models.DateTimeField(auto_now=True, verbose_name='Ekle Tarih'),
        ),
    ]
