# Generated by Django 3.1 on 2020-10-23 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201023_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='dategame',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 23, 14, 20, 7, 694569, tzinfo=utc), null=True, verbose_name='Ekle Tarih'),
        ),
    ]
