# Generated by Django 3.1 on 2020-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20201023_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
