# Generated by Django 3.1 on 2020-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20201023_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
