# Generated by Django 3.1 on 2020-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20201023_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='date',
            field=models.DateField(default='2020-10-01 12:00:00'),
        ),
    ]
