# Generated by Django 3.1 on 2020-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20201023_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='date',
            field=models.DateField(default=1),
        ),
    ]
