# Generated by Django 3.1 on 2020-10-23 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20201023_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
