# Generated by Django 3.1 on 2020-10-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0021_remove_mygame_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addgamemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Beğenme Tarih')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.oyunlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
