# Generated by Django 3.1 on 2020-10-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_addgamemy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addgamemy',
        ),
    ]
