# Generated by Django 3.1 on 2020-10-23 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0024_auto_20201023_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.oyunlar'),
        ),
        migrations.AlterField(
            model_name='mygame',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
