# Generated by Django 3.1 on 2020-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_messageuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygame',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Report Tarih'),
        ),
    ]
